package org.invenio.proyectoprograii.orm;
// Generated Feb 17, 2018 4:33:56 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Organizacion generated by hbm2java
 */
@Entity
@Table(name = "organizacion",
        catalog = "proyecto"
)
public class Organizacion implements java.io.Serializable {

    private String idCliente;
    private String nombre;
    private String direccion;
    private String correo;
    private String telefono;
    private int usuario;
    private Set<Usuario> usuarioses = new HashSet<Usuario>(0);

    public Organizacion() {
    }

    @Id

    @Column(name = "idCliente", unique = true, nullable = false, length = 30)
    public String getIdCliente() {
        return this.idCliente;
    }

    public void setIdCliente(String idCliente) {
        this.idCliente = idCliente;
    }

    @Column(name = "nombre", nullable = false, length = 45)
    public String getNombre() {
        return this.nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    @Column(name = "direccion", nullable = false, length = 45)
    public String getDireccion() {
        return this.direccion;
    }

    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }

    @Column(name = "correo", nullable = false, length = 45)
    public String getCorreo() {
        return this.correo;
    }

    public void setCorreo(String correo) {
        this.correo = correo;
    }

    @Column(name = "telefono", nullable = false, length = 45)
    public String getTelefono() {
        return this.telefono;
    }

    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }

    @Column(name = "usuario", nullable = false)
    public int getUsuario() {
        return this.usuario;
    }

    public void setUsuario(int usuario) {
        this.usuario = usuario;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "organizacion")
    public Set<Usuario> getUsuarioes() {
        return this.usuarioses;
    }

    public void setUsuarioes(Set<Usuario> usuarioses) {
        this.usuarioses = usuarioses;
    }

}
