/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.invenio.proyectoprograii.ui;

import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import org.invenio.proyectoprograii.orm.Usuario;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.ApplicationContext;
import org.springframework.context.annotation.ComponentScan;

/**
 *
 * @author maste
 */
@SpringBootApplication
@ComponentScan("org.invenio.proyectoprograii")
public class FrmEscritorio extends javax.swing.JFrame {

    /**
     * Creates new form frmEscritorio
     */
    private static ApplicationContext ctx;
    private Usuario usuario;

    public FrmEscritorio(ApplicationContext context) {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
        ctx = context;
    }

    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
        if(!usuario.getTipo().equals("Admin")){
            btnUsuario.setVisible(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        btnClientes = new javax.swing.JButton();
        btnFactura = new javax.swing.JButton();
        btnInventario = new javax.swing.JButton();
        btnUsuario = new javax.swing.JButton();
        escritorio = new javax.swing.JDesktopPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToolBar1.setRollover(true);

        btnClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/collaboration.png"))); // NOI18N
        btnClientes.setText("Clientes");
        btnClientes.setFocusable(false);
        btnClientes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnClientes.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClientesActionPerformed(evt);
            }
        });
        jToolBar1.add(btnClientes);

        btnFactura.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/pay.png"))); // NOI18N
        btnFactura.setText("Facturación");
        btnFactura.setFocusable(false);
        btnFactura.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnFactura.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFacturaActionPerformed(evt);
            }
        });
        jToolBar1.add(btnFactura);

        btnInventario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/trolley.png"))); // NOI18N
        btnInventario.setText("Inventario");
        btnInventario.setFocusable(false);
        btnInventario.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnInventario.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnInventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInventarioActionPerformed(evt);
            }
        });
        jToolBar1.add(btnInventario);

        btnUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/team.png"))); // NOI18N
        btnUsuario.setText("Usuarios");
        btnUsuario.setFocusable(false);
        btnUsuario.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnUsuario.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsuarioActionPerformed(evt);
            }
        });
        jToolBar1.add(btnUsuario);

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 430, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 706, Short.MAX_VALUE)
            .addComponent(escritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(escritorio))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClientesActionPerformed
        FrmCliente frmCliente = new FrmCliente(ctx);
        controlDeInstancia(frmCliente);
    }//GEN-LAST:event_btnClientesActionPerformed

    private void btnUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuarioActionPerformed
        FrmUsuario frmUsuario = new FrmUsuario(ctx);
        controlDeInstancia(frmUsuario);
    }//GEN-LAST:event_btnUsuarioActionPerformed

    private void btnFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFacturaActionPerformed
        FrmFacturacion frmFacturacion = new FrmFacturacion(ctx);
        frmFacturacion.setUsuario(usuario);
        controlDeInstancia(frmFacturacion);
    }//GEN-LAST:event_btnFacturaActionPerformed

    private void btnInventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInventarioActionPerformed
        FrmInventario frmInventario = new FrmInventario(ctx);
        controlDeInstancia(frmInventario);
    }//GEN-LAST:event_btnInventarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        //final ConfigurableApplicationContext context = new SpringApplicationBuilder(FrmEscritorio.class).headless(false).run(args);
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                FrmEscritorio frm = ctx.getBean(FrmEscritorio.class);
                frm.setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClientes;
    private javax.swing.JButton btnFactura;
    private javax.swing.JButton btnInventario;
    private javax.swing.JButton btnUsuario;
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables

    public void controlDeInstancia(JInternalFrame ifrm) {
        boolean mostrar = true;
        String nombre = ifrm.getTitle();
        for (int i = 0; i < escritorio.getComponentCount(); i++) {
            if (ifrm.getClass().isInstance(escritorio.getComponent(i))) {
                JOptionPane.showMessageDialog(rootPane, "La ventana " + nombre
                        + " que intenta abrir ya está abierta, cierre la "
                        + "ventana actual e intente nuevamente");
                ifrm.toFront();
                mostrar = false;
            }
        }
        if (mostrar) {
            escritorio.add(ifrm);
        }
        ifrm.show();
    }

}
