/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.invenio.proyectoprograii.ui;

import javax.swing.JOptionPane;
import org.invenio.proyectoprograii.orm.Organizacion;
import org.invenio.proyectoprograii.service.OrganizacionService;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.ApplicationContext;
import org.springframework.context.annotation.ComponentScan;

/**
 *
 * @author maste
 */
@SpringBootApplication
@ComponentScan("org.invenio.proyectoprograii")
public class FrmOrganizacion extends javax.swing.JInternalFrame {

    /**
     * Creates new form FrmOrganizacion
     */
    private final OrganizacionService organizacionService;

    public FrmOrganizacion(ApplicationContext context) {
        initComponents();
        organizacionService = context.getBean(OrganizacionService.class);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBuscar = new javax.swing.JButton();

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(119, 119, 119)
                .addComponent(btnBuscar)
                .addContainerGap(210, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(122, 122, 122)
                .addComponent(btnBuscar)
                .addContainerGap(133, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        Organizacion organizacion = new Organizacion();
        //organizacion = organizacionService.getOrganizacion("1");
        organizacion.setIdCliente("ABC1");
        organizacion.setNombre("Gimnasio");
        organizacion.setDireccion("Tilaran");
        organizacion.setCorreo("gimnasio@gmail.com");
        organizacion.setTelefono("86452136");
        organizacion.setUsuario(1);

        if (organizacionService.save(organizacion)) {
            JOptionPane.showMessageDialog(this, "Guardado");
        }

        //System.out.println("ORG: " + organizacion.toString());
    }//GEN-LAST:event_btnBuscarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    // End of variables declaration//GEN-END:variables
}
